BEGIN;

CREATE TYPE unit_types AS ENUM ('units_approximate', 'units_metric', 'units_imperial');

CREATE TABLE IF NOT EXISTS units_approximate (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  single TEXT UNIQUE,
  plural TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS units_metric (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  abbreviation TEXT UNIQUE,
  single TEXT UNIQUE,
  plural TEXT UNIQUE,
  to_imperial FLOAT
);

CREATE TABLE IF NOT EXISTS units_imperial (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  abbreviation TEXT UNIQUE,
  single TEXT UNIQUE,
  plural TEXT UNIQUE,
  to_metric FLOAT
);

CREATE TABLE IF NOT EXISTS ingredients (
  id uuid DEFAULT uuid_generate_v4() UNIQUE,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  amt FLOAT,
  ingredient TEXT NOT NULL,
  PRIMARY KEY (id, recipe_id)
);

CREATE TABLE IF NOT EXISTS ingredient_unit (
  ingredient_id uuid REFERENCES ingredients(id) ON DELETE CASCADE,
  unit_type unit_types NOT NULL,
  unit_approximate TEXT REFERENCES units_approximate(plural),
  unit_metric TEXT REFERENCES units_metric(plural),
  unit_imperial TEXT REFERENCES units_imperial(plural),
  PRIMARY KEY(ingredient_id)
);

COMMIT;