BEGIN;

CREATE TABLE IF NOT EXISTS units (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_set TEXT UNIQUE,
  unit_data jsonb
);

CREATE TABLE IF NOT EXISTS ingredients (
  id uuid DEFAULT uuid_generate_v4() UNIQUE,
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  amt FLOAT,
  unit_set TEXT REFERENCES units(unit_set) DEFAULT 'none',
  unit_data jsonb,
  ingredient TEXT NOT NULL,
  PRIMARY KEY (id, recipe_id)
);

COMMIT;