BEGIN;

CREATE TYPE unit_types AS ENUM ('units_approximate', 'units_metric', 'units_imperial');

CREATE TABLE IF NOT EXISTS units_approximate (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  single TEXT NOT NULL,
  plural TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS units_metric (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  abbreviation TEXT NOT NULL,
  single TEXT NOT NULL,
  plural TEXT NOT NULL,
  to_imperial FLOAT
);

CREATE TABLE IF NOT EXISTS units_imperial (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  abbreviation TEXT NOT NULL,
  single TEXT NOT NULL,
  plural TEXT NOT NULL,
  to_metric FLOAT
);

CREATE TABLE IF NOT EXISTS ingredients (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  amt FLOAT,
  unit_type unit_types,
  unit_id INTEGER,
  ingredient TEXT NOT NULL
);

ALTER TABLE
  recipes
DROP COLUMN ingredients;

COMMIT;