CREATE TYPE unit_class AS ENUM (
  'generic',
  'us',
  'metric'
)

CREATE TABLE IF NOT EXISTS ingredients_units (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  unit_name TEXT NOT NULL, 
  plural_name TEXT,
  unit_class unit_class,
  conversion FLOAT
);

CREATE TABLE IF NOT EXISTS ingredients (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  generic_amt FLOAT,
  metric_amt FLOAT,
  us_amt FLOAT,  
  unit REFERENCES ingredients_units,
  ingredient TEXT NOT NULL
);

ALTER TABLE recipes
  ADD COLUMN
    user_id uuid REFERENCES users(id)
    ON DELETE SET NULL;