TRUNCATE
  units
  RESTART IDENTITY CASCADE;

INSERT INTO
  units (unit_set, unit_data)
VALUES
  ('custom', '{"unit_single":"", "unit_plural":"Custom"}'),
  ('none', '{"unit_single":"", "unit_plural":""}'),
  ('x','{"unit_single":"x", "unit_plural":"x"}'),
  --approximate, measurable but not following a specific measurement system--
  ('bar','{ "class":"apprx", "unit_single":"bar", "unit_plural":"bars"}'),
  ('btl','{ "class":"apprx", "unit_single":"bottle", "unit_plural":"bottles"}'),
  ('bx','{ "class":"apprx", "unit_single":"box", "unit_plural":"boxes"}'),
  ('bowl','{ "class":"apprx", "unit_single":"bowl", "unit_plural":"bowls"}'),
  ('bnch','{ "class":"apprx", "unit_single":"bunch", "unit_plural":"bunches"}'),
  ('bush','{ "class":"apprx", "unit_single":"bushel", "unit_plural":"bushels"}'),
  ('can','{ "class":"apprx", "unit_single":"can", "unit_plural":"cans"}'),
  ('cs','{ "class":"apprx", "unit_single":"case", "unit_plural":"cases"}'),
  ('clv','{ "class":"apprx", "unit_single":"clove", "unit_plural":"cloves"}'),
  ('ct','{ "class":"apprx", "unit_single":"container", "unit_plural":"containers"}'),
  ('cb','{ "class":"apprx", "unit_single":"cube", "unit_plural":"cubes"}'),
  ('cut','{ "class":"apprx", "unit_single":"cut", "unit_plural":"cuts"}'),
  ('cting','{ "class":"apprx", "unit_single":"cutting", "unit_plural":"cuttings"}'),
  ('db','{ "class":"apprx", "unit_single":"dab", "unit_plural":"dabs"}'),
  ('dsh','{ "class":"apprx", "unit_single":"dash", "unit_plural":"dashes"}'),
  ('dc','{ "class":"apprx", "unit_single":"dice", "unit_plural":"dices"}'),
  ('dolp','{ "class":"apprx", "unit_single":"dollop", "unit_plural":"dollops"}'),
  ('drp','{ "class":"apprx", "unit_single":"drop", "unit_plural":"drops"}'),
  ('gls', '{ "class":"apprx", "unit_single":"glass", "unit_plural":"glasses"}'),
  ('hlv', '{ "class":"apprx", "unit_single":"half", "unit_plural":"halves"}'),
  ('hnd','{ "class":"apprx", "unit_single":"handful", "unit_plural":"handfuls"}'),
  ('jr','{ "class":"apprx", "unit_single":"jar", "unit_plural":"jars"}'),
  ('jg','{ "class":"apprx", "unit_single":"jug", "unit_plural":"jugs"}'),
  ('lef','{ "class":"apprx", "unit_single":"leaf", "unit_plural":"leaves"}'),
  ('lof','{ "class":"apprx", "unit_single":"loaf", "unit_plural":"loaves"}'),
  ('pkg','{ "class":"apprx", "unit_single":"package", "unit_plural":"packages"}'),
  ('pkt','{ "class":"apprx", "unit_single":"packet", "unit_plural":"packets"}'),
  ('prt','{ "class":"apprx", "unit_single":"part", "unit_plural":"parts"}'),
  ('pce','{ "class":"apprx", "unit_single":"piece", "unit_plural":"pieces"}'),
  ('pnch','{ "class":"apprx", "unit_single":"pinch", "unit_plural":"pinches"}'),
  ('pchr','{ "class":"apprx", "unit_single":"pitcher", "unit_plural":"pitchers"}'),
  ('qtr','{ "class":"apprx", "unit_single":"quarter", "unit_plural":"quarters"}'),
  ('scp','{ "class":"apprx", "unit_single":"scoop", "unit_plural":"scoops"}'),
  ('sec','{ "class":"apprx", "unit_single":"section", "unit_plural":"sections"}'),
  ('shk','{ "class":"apprx", "unit_single":"shake", "unit_plural":"shakes"}'),
  ('sht','{ "class":"apprx", "unit_single":"shot", "unit_plural":"shots"}'),
  ('slc','{ "class":"apprx", "unit_single":"slice", "unit_plural":"slices"}'),
  ('smdg','{ "class":"apprx", "unit_single":"smidgen", "unit_plural":"smidgens"}'),
  ('sqr','{ "class":"apprx", "unit_single":"square", "unit_plural":"squares"}'),
  ('splsh','{ "class":"apprx", "unit_single":"splash", "unit_plural":"splashes"}'),
  ('sprg','{ "class":"apprx", "unit_single":"sprig", "unit_plural":"sprigs"}'),
  ('sprnk','{ "class":"apprx", "unit_single":"sprinkle", "unit_plural":"sprinkles"}'),
  ('tin','{ "class":"apprx", "unit_single":"tin", "unit_plural":"tins"}'),
--TODO add conversion_ratio & conversion_unit 
('oz'    ,'{"class":"US", "cnv_to":"g",  "cnv_ratio":"28.3495", "unit_abbr":"oz"     , "unit_single":"ounce"      ,"unit_plural":"ounces"}'),
('lb'    ,'{"class":"US", "cnv_to":"kg", "cnv_ratio":".453592", "unit_abbr":"lb"     , "unit_single":"pound"      ,"unit_plural":"pounds"}'),
('tsp'   ,'{"class":"US", "cnv_to":"g",  "cnv_ratio":"10.5",    "unit_abbr":"tsp"    , "unit_single":"teaspoon"   ,"unit_plural":"teaspoons"}'),
('tbsp'  ,'{"class":"US", "cnv_to":"g",  "cnv_ratio":"14.3",    "unit_abbr":"tbsp"   , "unit_single":"tablespoon" ,"unit_plural":"tablespoons"}'),
('floz'  ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"29.5735", "unit_abbr":"floz"   , "unit_single":"fluid ounce","unit_plural":"fluid ounces"}'),
('qtcup' ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"59.14706","unit_abbr":"1/4 cup", "unit_single":"1/4 cup"    ,"unit_plural":"1/4 cups"}'),
('thdcup','{"class":"US", "cnv_to":"ml", "cnv_ratio":"78.8627", "unit_abbr":"1/3 cup", "unit_single":"1/3 cup"    ,"unit_plural":"1/3 cups"}'),
('hcup'  ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"118.294", "unit_abbr":"1/2 cup", "unit_single":"1/2 cup"    ,"unit_plural":"1/2 cups"}'),
('cup'   ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"236.588", "unit_abbr":"cup"    , "unit_single":"cup"        ,"unit_plural":"cups"}'),
('pt'    ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"473.176", "unit_abbr":"pt"     , "unit_single":"pint"       ,"unit_plural":"pints"}'),
('qrt'   ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"946.353", "unit_abbr":"qrt"    , "unit_single":"quart"      ,"unit_plural":"quarts"}'),
('hgal'  ,'{"class":"US", "cnv_to":"ml", "cnv_ratio":"1892.71", "unit_abbr":"hgal"   , "unit_single":"half gallon","unit_plural":"half gallons"}'),
('gal'   ,'{"class":"US", "cnv_to":"l",  "cnv_ratio":"3.78541", "unit_abbr":"gal"    , "unit_single":"gallon"     ,"unit_plural":"gallons"}'),
--TODO add conversion_ratio & conversion_unit
('mg','{"class":"Metric", "cnv_to":"oz",  "cnv_ratio":".035274", "unit_abbr":"mg","unit_single":"milligram" ,"unit_plural":"milligrams"}'),
('g' ,'{"class":"Metric", "cnv_to":"oz",  "cnv_ratio":".035274", "unit_abbr":"g" ,"unit_single":"gram"      ,"unit_plural":"grams"}'),
('kg','{"class":"Metric", "cnv_to":"lb",  "cnv_ratio":"2.20462", "unit_abbr":"kg","unit_single":"kilogram"  , "unit_plural":"kilograms"}'),
('ml','{"class":"Metric", "cnv_to":"floz","cnv_ratio":".033814", "unit_abbr":"ml", "unit_single":"milliliter", "unit_plural":"milliliters"}'),
('l' ,'{"class":"Metric", "cnv_to":"gal", "cnv_ratio":"2.20462", "unit_abbr":"l" ,"unit_single":"liter"     , "unit_plural":"liters"}');
-- ('met_dl','{"class":"met", "unit_abbr":"dl","unit_single":"deciliter" , "unit_plural":"deciliters"}'); -- TODO: finer units?